### ISSUE TITLE
Repo FTP server down

### ISSUE THREAD

**Issue by ostrich** [ericwoud/buildRKarch#1]
Running `./build.sh -F` for a BPI-R3 SD card installation gives the error below. I also can't connect to the server via anonymous FTP using a separate client.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ftp.woudstra.mywire.org port 21 after 156 ms: Couldn't connect to server
```

I tried editing `build.sh` to comment out `REPOURL` and rename `BACKUPREPOURL` to `REPOURL` but that made `curl` do this over and over with no indication of success.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0    166      0 --:--:-- --:--:-- --:--:--   169
```

Networking and DNS is otherwise working.

**Comment by ericwoud** [comment]
Thanks for reporting. I have updated the backup repo, so pacman should be able to get everything from there.

I will look into the ftp server as soon as I can.

I will also take a look to the script if it handles downloading pacman.static correctly in case the server is down, which it probably does not, this part is quite new. I will need to add some code, as the backup repo is not ftp, but http.

**Comment by ericwoud** [comment]
I've changed the code that initially pacman-static will be downloaded from backup-repo (github). Unfortionally I cannot test it right now, but this should work.

That should fix it for now. When the system is bootstrapped, it should use the backup-repo, if the ftp server is down.

I'll later check the ftp server, but it should normally be not a big deal if it is down.

**Comment by ostrich** [comment]
Now getting stuck on

```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
 aur is up to date
 ericwoud is up to date
error: failed retrieving file 'ericwoud.db' from ftp.woudstra.mywire.org : Failed to connect to ftp.woudstra.mywire.org port 21 after 106 ms: Couldn't connect to server
```

**Comment by ericwoud** [comment]
I guess it passed the `pacman` command at line 219 and now is stuck at line 221.

Too bad I can't try out myself at the moment, but you could try at line 221:

Replace `pacman -Syu` by `pacman -Syyu`

Similar to line 219.

It should continue with the backupserver's url

**Comment by ericwoud** [comment]
Server is back online, it turned out I ran in to this problem:

https://unix.stackexchange.com/a/729419

Should run fine now the server, also after reboot.

But anyway, I will still check the script for the case the server is not online. I'll leave the issue open for now.

Thanks!

**Comment by ostrich** [comment]
It worked, thanks! FWIW it was line 240 I had to edit, not 221.

**Comment by ericwoud** [comment]
240? Then I guess you are using buildR64arch instead of buildRKarch, which use the same repo.

**Comment by ostrich** [comment]
Huh, yeah, I am using buildR64arch. Actually I have no idea how I got to buildRKarch to report the bug here. Weird 😅. All's well that ends well though.

**Comment by ericwoud** [comment]
This repo may add bananapi W3 one day... So maybe cya later. Don't forget to ⭐

**Comment by ericwoud** [comment]
Now only pacman is used with -Syyu
