### ISSUE TITLE
pacman-static is downloaded but failed to execute

### ISSUE THREAD

**Issue by gcd0318** [ericwoud/buildRKarch#4]
I got following error when executing line 190:
```
unshare: failed to execute pacman-static: No such file or directory
```
but pacman-static is in rootfs/usr/bin
I'm not sure if $schroot worked well

**Comment by ericwoud** [comment]
All executables in the chroot need to be run with qemu-aarch64-static (if running from x86_64). You will get that error if it is run without. It is setup with the command:
```
./build.sh -a
```
Did you run this command, if yes, what is your system? Which processor and which linux?

**Comment by ericwoud** [comment]
Without response, I cannot further investigate this issue. Closing.
