### ISSUE TITLE
github release should be update

### ISSUE THREAD

**Issue by F-TD5X** [ericwoud/buildRKarch#7]
seems it's way behind the ftp repo.

**Comment by ericwoud** [comment]
Thanks for reporting.

I am now working on a new way of handling the colon in some of the filenames.

If that is successful it will be much easier to keep the repo's in sync.

So, I'll leave the issue open for now and expect to close it within one or two weeks.

**Comment by ericwoud** [comment]
Found `rewritefs` for a solution to handling colons in the filename.

The backup repo is updated and will be updated montly.
