### ISSUE TITLE
rockchip-postinstall

### ISSUE THREAD

**Issue by Schlunze** [ericwoud/buildRKarch#8]
Hi,

i followed the guide and installed alarm on nvme.
Deployment step "rockchip-postinstall" produces many errors and trying to download depencys in a loop.
```
...
:: unable to satisfy dependency 'libjxl.so=0.10-64' required by ffmpeg-v4l2-request-git
:: unable to satisfy dependency 'ffmpeg' required by kodi-ext-git
:: unable to satisfy dependency 'kodi-ext-git' required by kodi-ext-git-dev
...
```
is there a quick fix for this issue?

Greetings Schnabulator.

**Comment by ericwoud** [comment]
Probably need to rebuild the package, see my archlinuxarm-repo and checkout the correct branch.

I haven't rebuild for a whille...

**Comment by ericwoud** [comment]
ffmpeg-v4l2-request-git is rebuild in the repo, so should be ok now.

**Comment by Schlunze** [comment]
nice thank you
